### PR TITLE
Fix image URL-s in README

### PR DESCRIPTION
**Pull request by szepeviktor**
This will work everywhere.

### CODE REVIEW

**Comment by szepeviktor** [comment]
BTW `/.github/raw/master/.github/` is a bit weird.
Images could live in a directory called "assets".

**Comment by adamlaki** [comment]
Thanks, Viktor, I fixed it in the meantime to root-relative.

**Comment by szepeviktor** [comment]
All right.
That does not work on this page
https://github.com/conedevelopment/.github/blob/master/profile/README.md

**Comment by adamlaki** [comment]
Ohh... Thanks, I made a commit (for some reason, I can't reopen this).

**Pull request closed without merging**
