### PR TITLE
Fix header levels in README

### PR DESCRIPTION
**Pull request by szepeviktor**
@adamlaki H1>H2 ...

### CODE REVIEW

**Comment by szepeviktor** [comment]
# I know - I know

That thin gray line!

**Comment by adamlaki** [comment]
Viktor, if this document is rendered into the DOM then there will be to `<h1>`, not?

**Comment by szepeviktor** [comment]
This PR creates one H1 and one H2 elements.

**Comment by adamlaki** [comment]
image

We have an `<h1>` at the destination.

**Comment by szepeviktor** [comment]
I see!!

**Pull request closed without merging**
